In [1]:
import ccdc
import os
import sys
import csv
import argparse
import pandas as pd
from tabulate import tabulate
from ccdc.descriptors import CrystalDescriptors
import glob
from ccdc import crystal
#############################################################################################
folder = "/home/phunguyen/forCSDAnalysis/Exp/"
dest = "/home/phunguyen/Documents/CDSana/output_Exp.csv"
dest2 = "/home/phunguyen/Documents/CDSana/output_Exp.txt"

In [6]:
calculator = CrystalDescriptors.HBondCoordination()
with open("/home/phunguyen/forCSDAnalysis/Exp/Wu_LS_NaMPSAvesta.cif") as f:
        s = f.read()
c = crystal.Crystal.from_string(s,format='cif')

In [7]:
c

In [10]:
GSA = CrystalDescriptors.GraphSetSearch()
settings = GSA.settings

In [13]:
settings.distance_range = (-5,1.0)

In [14]:
settings.distance_range

(-5.0, 1.0)

In [4]:
pd.read_csv("/home/phunguyen/Documents/CDSana/output_vdw.csv")["Propensities"]

0       functional groups  donors                  ...
1       functional groups  donors                  ...
2       functional groups  donors                  ...
3       functional groups  donors                  ...
4      functional groups  donors           acceptor...
Name: Propensities, dtype: object

In [6]:
pd.read_table("/home/phunguyen/Documents/CDSana/output_vdw.txt")

/home/phunguyen/anaconda3/envs/matsci_py27/lib/python2.7/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.

    +----+---------------------------------------------------------+-------------------------------------------------------------+---------------+---------------+-----------------------------+
0    |    | Propensities                           ...
1    |----+----------------------------------------...
2    |  0 | functional groups  donors              ...
3    |    | 0              T3OH0     NaN         O(...
4    |    | 1              T2OH0     NaN         O(...
5    |    | 2       T3NH0_cyclic     NaN         O(...
6    |    | 3              T1OH0     NaN         O(...
7    |    | 4              T1NH0     NaN         O(...
8    |    | 5                NaN     NaN         O(...
9    |    | 6                NaN     NaN         O(...
10   |    | 7                NaN     NaN         O(...
11   |    | 8                NaN     NaN         O(...
12   |    | 9                NaN     NaN         O(...
13   |    | 10               NaN     NaN         O(...
14   |    | 11               NaN     NaN         O(...
15   |    | 12               NaN     NaN  N(atom 0 ...
16   |    | 13               NaN     NaN  N(atom 0 ...
17   |    | 14               NaN     NaN  N(atom 0 ...
18   |    | 15               NaN     NaN  N(atom 0 ...
19   |    | 16               NaN     NaN         O(...
20   |    | 17               NaN     NaN         O(...
21   |    | 18               NaN     NaN         O(...
22   |    | 19               NaN     NaN         O(...
23   |    | 20               NaN     NaN         O(...
24   |    | 21               NaN     NaN         O(...
25   |    | 22               NaN     NaN         O(...
26   |    | 23               NaN     NaN         N(...
27   |    | 24               NaN     NaN         O(...
28   |    | 25               NaN     NaN         O(...
29   |    | 26               NaN     NaN         O(...
..                                                 ...
164  |    | 22               NaN     NaN           ...
165  |    | 23               NaN     NaN           ...
166  |    | 24               NaN     NaN         O(...
167  |    | 25               NaN     NaN         O(...
168  |    | 26               NaN     NaN         O(...
169  |    | 27               NaN     NaN         O(...
170  |    | 28               NaN     NaN         O(...
171  |    | 29               NaN     NaN         O(...
172  |    | 30               NaN     NaN         O(...
173  |    | 31               NaN     NaN         O(...
174  |    | 32               NaN     NaN         O(...
175  |    | 33               NaN     NaN         O(...
176  |    | 34               NaN     NaN         O(...
177  |    | 35               NaN     NaN         O(...
178  |    | 36               NaN     NaN         N(...
179  |    | 37               NaN     NaN         N(...
180  |    | 38               NaN     NaN         N(...
181  |    | 39               NaN     NaN         N(...
182  |  4 | functional groups  donors           acc...
183  |    | 0             T3OH0     NaN  O(atom 0 o...
184  |    | 1             T2OH0     NaN  O(atom 0 o...
185  |    | 2             T1OH0     NaN  O(atom 0 o...
186  |    | 3             T1NH0     NaN  O(atom 0 o...
187  |    | 4               NaN     NaN  O(atom 0 o...
188  |    | 5               NaN     NaN  O(atom 0 o...
189  |    | 6               NaN     NaN  O(atom 0 o...
190  |    | 7               NaN     NaN  O(atom 0 o...
191  |    | 8               NaN     NaN  N(atom 0 o...
192  |    | 9               NaN     NaN  N(atom 0 o...
193  +----+----------------------------------------...

[194 rows x 1 columns]